pipeline {
    agent any

    environment {
        ECR_REPO = "326991552997.dkr.ecr.ap-northeast-2.amazonaws.com/test-cicd"
        NAME = "withmarket-item-server"
    }

    stages {
        stage("========== Test the project ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'cd presentation'
                    sh 'chmod 755 ./gradlew'
                    sh './gradlew clean test'
                }
            }

            post {
                success {
                    echo 'The Test stage is done successfully.'
                }

                failure {
                    echo 'The Test stage is fail.'
                }
            }
        }

        stage("========== Build the project ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'cd presentation'
                    sh './gradlew build'
                }
            }

            post {
                success {
                    echo 'The Build stage is done successfully.'
                }

                failure {
                    echo 'The Build stage is fail.'
                }
            }
        }

        stage("========== Build Docker Image ==========") {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'cd ./presentation/'
                    sh 'docker build -t ${NAME} .'
                    sh 'docker tag ${NAME}:latest ${ECR_REPO}:latest'
                }
            }
        }
    }

    post {
        success {
            slackSend(
                channel: "#server-build-history",
                color: "good",
                message: "[Successful] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }

        failure {
            slackSend(
                channel: "#server-build-history",
                color: "danger",
                message: "[Failed] Job:${env.JOB_NAME}, Build num:#${env.BUILD_NUMBER} @channel (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        }
    }
}
